from book_rental.views.user_index import UserIndex 
from book_rental.views.bookinfo_list_view import BookInfoListView 
from book_rental.views.bookinfo_detail_view import BookInfoDetailView 
from book_rental.views.rental import rental
from book_rental.views.overdue import overdue
from book_rental.views.book_return import book_return
from book_rental.views.return_check import return_check
from book_rental.views.wish_book import wish_book
from book_rental.views.wish_cancel import wish_cancel
