# Generated by Django 2.2.1 on 2019-07-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manager', '0001_initial'),
        ('book_manager', '0002_auto_20190702_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='book_manager.Book')),
                ('bookinfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book_manager.BookInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_manager.User')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField()),
                ('return_deadline', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book_manager.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_manager.User')),
            ],
        ),
    ]
