# Generated by Django 2.2.1 on 2019-07-02 07:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manager', '0001_initial'),
        ('book_manager', '0002_auto_20190702_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('comment', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('bookinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='book_manager.BookInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_manager.User')),
            ],
        ),
    ]
