# Generated by Django 2.2.1 on 2019-06-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('nickname', models.CharField(max_length=10, unique=True, verbose_name='닉네임')),
                ('team', models.CharField(choices=[('개발', '개발팀'), ('경영지원', '경영지원팀'), ('디자인', '디자인팀'), ('영업', '영업팀'), ('운영', '운영팀'), ('재무', '재무팀'), ('대표', 'CEO'), ('기타', '기타')], default='개발', max_length=10, verbose_name='부서')),
                ('bio', models.CharField(blank=True, max_length=200, verbose_name='소개')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생일')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
