# Generated by Django 2.2.1 on 2019-06-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('tel', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('birthday', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('join_date', models.DateField()),
                ('leave_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
