from book_manager.views.index import Index
from book_manager.views.book_create_view import BookCreateView
from book_manager.views.book_detail_view import BookDetailView
from book_manager.views.book_info_create_view import BookInfoCreateView
from book_manager.views.book_info_detail_view import BookInfoDetailView
from book_manager.views.book_info_list_view import BookInfoListView
from book_manager.views.book_info_update_view import BookInfoUpdateView
from book_manager.views.book_list_view import BookListView
from book_manager.views.book_update_view import BookUpdateView
from book_manager.views.isbn_search import isbnSearch